name: NPM
on:
  schedule:
    - cron: '0 0 * * 0'
jobs:
  npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7
      - run: |
          git config --local user.name "GitHub"
          git config --local user.email "noreply@github.com"
          bin/npm
